name: test

on: push

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/feature' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo Hello

